version: '3'

services:
  startup:
    # image: "brianoflondon/guid-slurp:develop"
    build:
      context: .
      dockerfile: Dockerfile
    command: [
      "python", "guid_slurp/startup.py"
    ]
    container_name: "guid-slurp-start"
    networks:
      - guid-slurp-internal
    env_file:
      - .env
    volumes:
      - guid-slurp-data:/app/data
    restart: no
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: [
      "gunicorn", "guid_slurp.main:app",
      "--proxy-protocol",
      "--workers", "4",
      "--worker-class", "uvicorn.workers.UvicornWorker",
      "--bind", "0.0.0.0:80"
    ]
    container_name: "guid-slurp-api"
    networks:
      - v4vapp-frontend-v2-traefik_traefik-public-p51
      - guid-slurp-traefik
      - guid-slurp-internal
    env_file:
      - .env
    ports:
      - ${API_PORT}:80
    volumes:
      - guid-slurp-data:/app/data
    labels:
      # Enable Traefik for this specific "api" service
      - traefik.enable=true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"

  mongodb:
    container_name: guid-slurp-mongodb
    hostname: mongodb
    image: mongo:latest
    env_file:
      - ".env"
    ports:
      # If you want to connect to the MongoDB from outside the Docker network
      # Uncomment the following line and change
      - "${MONGODB_CONNECTION_IP}:27017"
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    networks:
      - guid-slurp-internal


networks:
  guid-slurp-traefik:
    driver: bridge
  guid-slurp-internal:
    driver: bridge

  v4vapp-frontend-v2-traefik_traefik-public-p51:
    external: true

volumes:
  traefik-ssl-certs:
    driver: local

  mongodb-data:
    driver: local

  guid-slurp-data:
    driver: local
